pipeline {
    agent none
    stages {    
        stage ('Jenkins credentials to docker') {
            agent {
                docker {
                    image 'mesosphere/aws-cli:latest'
                    args '-v $WORKSPACE:/tmp -u="root"'
                }
            }

            environment {
                AWS_ACCESS_KEY_ID  =  credentials('AWS_ACCESS_KEY_ID')
                AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
                AWS_DEFAULT_REGION = credentials('AWS_DEFAULT_REGION')
                ///AWS_SHARED_CREDENTIALS_FILE 
            }     

            steps {
                sh "echo $GIT_USERNAME : $GIT_PASSWORD : $AWS_ACCESS_KEY_ID  > /tmp/echo.txt"
                sh '''
                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                    export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

                    aws --version
                '''
                }
        }
    }
}