# Default values for website2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  #repository: bitnami/apache
  repository: httpd
  tag: 2.4
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
