apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-sc
provisioner: kubernetes.io/aws-ebs
parameters: 
  fsType: ext4
  type: gp2
volumeBindingMode: WaitForFirstConsumer
# allowedTopologies:
# - matchLabelExpressions:
#   - key: failure-domain.beta.kubernetes.io/zone
#     values:
#     - us-east1-a
